### ISSUE TITLE
cuda-memcheck hanging for PR#8

### ISSUE THREAD

**Issue by beiwang2003** [SegmentLinking/TrackLooper#11]
cuda-memcheck is hanging for: https://github.com/SegmentLinking/TrackLooper/commit/ed6e48e3133cd4e435e8dc8e6a3ffaecc218b739. This is potentially due to large numbers of cudaMalloc and cudaFree to implement the Pixel segments. 
If we comment out https://github.com/tresreid/TrackLooper/blob/explicit_hits/bin/doAnalysis.cc#L747
and
https://github.com/tresreid/TrackLooper/blob/explicit_hits/bin/doAnalysis.cc#L753
we should be able to run cuda-memcheck again and there will be a normal amount of cuda calls.

**Comment by tresreid** [comment]
Hi @beiwang2003 . The issue is due to this line: https://github.com/SegmentLinking/TrackLooper/blob/master/SDL/Event.cu#L1493
You would need to comment out the "+ 1" since that refers to the pixel index and we have commented out loading the pixels to get cuda-memcheck to run. Commenting this out doesn't report errors to cuda-memcheck. Idk if this will cause an issue if the pixels were included (since cuda-memcheck hangs at the pixel loading), but we can revisit this when the pixels are redone in a better manner. I think that will avoid the hanging issue since there would be less cuda calls.

**Comment by beiwang2003** [comment]
@tresreid the links in the first comment are broken. Can you fix it?

**Comment by beiwang2003** [comment]
@tresreid commenting out https://github.com/SegmentLinking/TrackLooper/blob/master/SDL/Event.cu#L1493 does not help with cuda-memcheck. The code still failed with the same segmentation violation error.

**Comment by tresreid** [comment]
@beiwang2003 did you comment out the whole line or just the +1?

**Comment by beiwang2003** [comment]
> @beiwang2003 did you comment out the whole line or just the +1?

@tresreid they whole line.

**Comment by tresreid** [comment]
just the +1 is what you need to comment out
