### ISSUE TITLE
Performance Plots Are Not Deterministic

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#265]
If you run the master branch twice over the same events and create performance plots you get slightly different efficiencies each time. See below for example with the current master branch.

![TC_base_0_0_eff_ptzoom](https://user-images.githubusercontent.com/25272611/230644428-bbd97560-e6ff-4e8d-9e7b-c8d4ad02fd42.png)

**Comment by VourMa** [comment]
Do we still think this is an issue? I believe that the coming of the CPU version showed us that the performance plots are deterministic.

**Comment by GNiendorf** [comment]
Andres has done a lot of excellent work making the cpu/gpu difference minimal and making the code more reproducible because of that, but there are still small differences on the GPU backend if you rerun the code so I think this issue should remain open for now. @ariostas You've looked at this more than anyone now, do you know for sure what is causing these small differences? Not really important but probably good to keep in mind.

Difference on our current master:
![TC_base_0_0_eff_ptzoom](https://github.com/SegmentLinking/TrackLooper/assets/25272611/e924a7c6-2a78-4d29-9512-751b1eee1d8c)

**Comment by VourMa** [comment]
> there are still small differences on the GPU backend if you rerun the code

But that can't be avoided on GPU as long as we have truncations in our code, as different things may get truncated in different runs. This is not unexpected behavior. I would see a problem if there were differences without truncations in the GPU backend, or if there were differences in the CPU backend.

**Comment by ariostas** [comment]
I changed some stuff to avoid truncation, and it seems like that's the reason. You can see the plots comparing two runs [here](https://www.classe.cornell.edu/~ar2285/www/LST/comparison_no_truncation/summary/). They look pretty much identical, although in some plots there are some super tiny differences, and I'm not sure why.

However, one thing we might want to look into is that for some objects (especially segments and triplets) I had to increase maximum occupancy by a huge amount in order to avoid truncating. It might be that we're truncating a significant portion of objects. It could be that the code has changed significantly since the occupancy bounds were chosen.

**Comment by GNiendorf** [comment]
@ariostas Closing this PR, thank you for fixing so many issues associated with this.
