### ISSUE TITLE
Skip some modules?

### ISSUE THREAD

**Issue by sgnoohc** [SegmentLinking/TrackLooper#82]
Do I understand it correctly that this will cause to skip some modules?
The gridDim.x * blockDim.x is some non-unity steps. (I think 256? because the kernel is called with 16,16 dimensions)
But doesn't this mean, that the last less than 255 modules will be skipped?

https://github.com/SegmentLinking/TrackLooper/blob/2126c050b9c8d878c495d2b448cb7d1552665fea/SDL/Kernels.cu#L2422

**Comment by sgnoohc** [comment]
Just to note: I think there are similar things happening in different places.

**Comment by sgnoohc** [comment]
Maybe it turns out ok because last modurls are typically outer layer?

**Comment by tresreid** [comment]
I dont think so, since this is being launched for each thread. So even though for each thread you are skipping quite a few, with all threads you should get every number from 0 to nLowerModules. and the inner loop is not thread based so all comparisons should be made. 
That is to say there are threads 0-255 being launched, and each one goes through the for loop with a step of 256. so you get 0-255 the first iteration, then 256-511 the second and so on.

**Comment by sgnoohc** [comment]
I don't think that's true. 
The steps in the += is size 256

i.e. the following line jumps by 256.
```lowmod1+=blockDim.x*gridDim.x```

**Comment by sgnoohc** [comment]
ah ok.
